services:
  php:
    build:
      context: ./docker/php
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/var
    working_dir: /var/www/html
    ports:
      - "9001:9000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: ${APP_NAME}_mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  mysql_data:
